import {Language } from '../types';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    title: 'EDUGRANT',
    home: 'Home',
    browse: 'Scholarships',
    dashboard: 'Dashboard',
    login: 'Login / Sign Up',
    logout: 'Logout',
    apply: 'Apply Now',
    applyPrompt: 'Please login to apply',
    searchPlaceholder: 'Search scholarships...',
    heroTitle: 'Empowering Your Future',
    heroDesc: 'Find and apply for the best scholarships in India. A centralized platform to manage your academic funding journey.',
    filter: 'Filter',
    deadline: 'Deadline',
    amount: 'Amount',
    eligibility: 'Eligibility',
    status: 'Status',
    welcome: 'Welcome',
    profileSetup: 'Complete Profile',
    college: 'College Name',
    cgpa: 'Current CGPA',
    class12: 'Class 12 Marks (%)',
    submit: 'Submit',
    emailPlaceholder: 'Enter your email',
    otpPlaceholder: 'Enter OTP',
    getOtp: 'Get OTP',
    verify: 'Verify & Login',
    featureSearchTitle: 'Easy Search',
    featureSearchDesc: 'Find scholarships tailored to your academic profile.',
    featureApplyTitle: 'One-Click Apply',
    featureApplyDesc: 'Streamlined application process for verified students.',
    featureTrackTitle: 'Track Status',
    featureTrackDesc: 'Real-time updates on your application progress.'
  },
  hi: {
    title: 'एडुआनुदान',
    home: 'होम',
    browse: 'छात्रवृत्तियां',
    dashboard: 'डैशबोर्ड',
    login: 'लॉगिन / साइन अप',
    logout: 'लॉग आउट',
    apply: 'आवेदन करें',
    applyPrompt: 'आवेदन करने के लिए लॉगिन करें',
    searchPlaceholder: 'छात्रवृत्ति खोजें...',
    heroTitle: 'अपने भविष्य को सशक्त बनाएं',
    heroDesc: 'भारत में सर्वश्रेष्ठ छात्रवृत्तियां खोजें और आवेदन करें। अपनी शैक्षणिक फंडिंग यात्रा को प्रबंधित करने के लिए एक केंद्रीकृत मंच।',
    filter: 'फ़िल्टर',
    deadline: 'अंतिम तिथि',
    amount: 'राशि',
    eligibility: 'पात्रता',
    status: 'स्थिति',
    welcome: 'स्वागत है',
    profileSetup: 'प्रोफ़ाइल पूरी करें',
    college: 'कॉलेज का नाम',
    cgpa: 'वर्तमान CGPA',
    class12: 'कक्षा 12 के अंक (%)',
    submit: 'जमा करें',
    emailPlaceholder: 'अपना ईमेल दर्ज करें',
    otpPlaceholder: 'ओटीपी दर्ज करें ',
    getOtp: 'ओटीपी प्राप्त करें',
    verify: 'सत्यापित करें',
    featureSearchTitle: 'आसान खोज',
    featureSearchDesc: 'अपनी शैक्षणिक प्रोफ़ाइल के अनुरूप छात्रवृत्तियां खोजें।',
    featureApplyTitle: 'एक क्लिक आवेदन',
    featureApplyDesc: 'सत्यापित छात्रों के लिए सरल आवेदन प्रक्रिया।',
    featureTrackTitle: 'स्थिति ट्रैक करें',
    featureTrackDesc: 'अपने आवेदन की प्रगति पर रीयल-टाइम अपडेट।'
  },
  bn: {
    title: 'এডুগ্রান্ট',
    home: 'হোম',
    browse: 'বৃত্তি',
    dashboard: 'ড্যাশবোর্ড',
    login: 'লগইন / সাইন আপ',
    logout: 'লগ আউট',
    apply: 'আবেদন করুন',
    applyPrompt: 'আবেদন করতে লগইন করুন',
    searchPlaceholder: 'বৃত্তি খুঁজুন...',
    heroTitle: 'আপনার ভবিষ্যৎ ক্ষমতায়ন করুন',
    heroDesc: 'ভারতে সেরা বৃত্তি খুঁজুন এবং আবেদন করুন। আপনার একাডেমিক ফান্ডিং যাত্রা পরিচালনা করার জন্য একটি কেন্দ্রীয় প্ল্যাটফর্ম।',
    filter: 'ফিল্টার',
    deadline: 'শেষ তারিখ',
    amount: 'পরিমাণ',
    eligibility: 'যোগ্যতা',
    status: 'অবস্থা',
    welcome: 'স্বাগতম',
    profileSetup: 'প্রোফাইল সম্পূর্ণ করুন',
    college: 'কলেজের নাম',
    cgpa: 'বর্তমান সিজিপিএ',
    class12: 'দ্বাদশ শ্রেণীর নম্বর (%)',
    submit: 'জমা দিন',
    emailPlaceholder: 'আপনার ইমেল দিন',
    otpPlaceholder: 'ওটিপি দিন ',
    getOtp: 'ওটিপি পান',
    verify: 'যাচাই করুন',
    featureSearchTitle: 'সহজ অনুসন্ধান',
    featureSearchDesc: 'আপনার শিক্ষাগত প্রোফাইলের সাথে মানানসই বৃত্তি খুঁজুন।',
    featureApplyTitle: 'এক ক্লিকে আবেদন',
    featureApplyDesc: 'যাচাইকৃত শিক্ষার্থীদের জন্য সহজ আবেদন প্রক্রিয়া।',
    featureTrackTitle: 'স্ট্যাটাস ট্র্যাক করুন',
    featureTrackDesc: 'আপনার আবেদনের অগ্রগতির রিয়েল-টাইম আপডেট।'
  },
  ta: {
    title: 'எடுக்ராண்ட்',
    home: 'முகப்பு',
    browse: 'உதவித்தொகை',
    dashboard: 'டாஷ்போர்டு',
    login: 'உள்நுழை / பதிவு',
    logout: 'வெளியேறு',
    apply: 'விண்ணப்பிக்கவும்',
    applyPrompt: 'விண்ணப்பிக்க உள்நுழையவும்',
    searchPlaceholder: 'உதவித்தொகையைத் தேடுங்கள்...',
    heroTitle: 'உங்கள் எதிர்காலத்தை மேம்படுத்துங்கள்',
    heroDesc: 'இந்தியாவில் சிறந்த உதவித்தொகைகளைக் கண்டறிந்து விண்ணப்பிக்கவும். உங்கள் கல்வி நிதி பயணத்தை நிர்வகிக்க ஒரு மையப்படுத்தப்பட்ட தளம்.',
    filter: 'வடிகட்டி',
    deadline: 'கடைசி தேதி',
    amount: 'தொகை',
    eligibility: 'தகுதி',
    status: 'நிலை',
    welcome: 'வரவேற்கிறோம்',
    profileSetup: 'சுயவிவரத்தை முடிக்கவும்',
    college: 'கல்லூரி பெயர்',
    cgpa: 'தற்போதைய CGPA',
    class12: 'வகுப்பு 12 மதிப்பெண்கள் (%)',
    submit: 'சமர்ப்பிக்கவும்',
    emailPlaceholder: 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    otpPlaceholder: 'OTP ஐ உள்ளிடவும் ',
    getOtp: 'OTP பெறவும்',
    verify: 'சரிபார்த்து உள்நுழையவும்',
    featureSearchTitle: 'எளிதான தேடல்',
    featureSearchDesc: 'உங்கள் கல்விச் சுயவிவரத்திற்கு ஏற்ற உதவித்தொகையைக் கண்டறியவும்.',
    featureApplyTitle: 'ஒரே கிளிக் விண்ணப்பம்',
    featureApplyDesc: 'சரிபார்க்கப்பட்ட மாணவர்களுக்கான எளிமையான விண்ணப்ப செயல்முறை.',
    featureTrackTitle: 'நிலையை கண்காணிக்கவும்',
    featureTrackDesc: 'உங்கள் விண்ணப்ப முன்னேற்றம் குறித்த நேரடி அறிவிப்புகள்.'
  },
  or: {
    title: 'ଏଡୁଗ୍ରାଣ୍ଟ',
    home: 'ମୁଖ୍ୟ ପୃଷ୍ଠା',
    browse: 'ଛାତ୍ରବୃତ୍ତି',
    dashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    login: 'ଲଗ୍ ଇନ୍ / ସାଇନ୍ ଅପ୍',
    logout: 'ଲଗ୍ ଆଉଟ୍',
    apply: 'ଆବେଦନ କରନ୍ତୁ',
    applyPrompt: 'ଆବେଦନ କରିବାକୁ ଲଗ୍ ଇନ୍ କରନ୍ତୁ',
    searchPlaceholder: 'ଛାତ୍ରବୃତ୍ତି ଖୋଜନ୍ତୁ...',
    heroTitle: 'ଆପଣଙ୍କ ଭବିଷ୍ୟତକୁ ସଶକ୍ତ କରନ୍ତୁ',
    heroDesc: 'ଭାରତରେ ସର୍ବୋତ୍ତମ ଛାତ୍ରବୃତ୍ତି ଖୋଜନ୍ତୁ ଏବଂ ଆବେଦନ କରନ୍ତୁ |',
    filter: 'ଫିଲ୍ଟର୍',
    deadline: 'ଶେଷ ତାରିଖ',
    amount: 'ପରିମାଣ',
    eligibility: 'ଯୋଗ୍ୟତା',
    status: 'ସ୍ଥିତି',
    welcome: 'ସ୍ୱାଗତ',
    profileSetup: 'ପ୍ରୋଫାଇଲ୍ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ',
    college: 'କଲେଜ ନାମ',
    cgpa: 'ବର୍ତ୍ତମାନର CGPA',
    class12: 'ଦ୍ୱାଦଶ ଶ୍ରେଣୀ ମାର୍କ (%)',
    submit: 'ଦାଖଲ କରନ୍ତୁ',
    emailPlaceholder: 'ଆପଣଙ୍କ ଇମେଲ୍ ଦିଅନ୍ତୁ',
    otpPlaceholder: 'OTP ଦିଅନ୍ତୁ ',
    getOtp: 'OTP ପାଆନ୍ତୁ',
    verify: 'ଯାଞ୍ଚ କରି ଲଗ୍ ଇନ୍ କରନ୍ତୁ',
    featureSearchTitle: 'ସହଜ ଅନୁସନ୍ଧାନ',
    featureSearchDesc: 'ଆପଣଙ୍କର ଏକାଡେମିକ୍ ପ୍ରୋଫାଇଲ୍ ଅନୁଯାୟୀ ଛାତ୍ରବୃତ୍ତି ଖୋଜନ୍ତୁ |',
    featureApplyTitle: 'ଗୋଟିଏ କ୍ଲିକ୍ ଆବେଦନ',
    featureApplyDesc: 'ଯାଞ୍ଚ ହୋଇଥିବା ଛାତ୍ରମାନଙ୍କ ପାଇଁ ସରଳ ଆବେଦନ ପ୍ରକ୍ରିୟା |',
    featureTrackTitle: 'ସ୍ଥିତି ଟ୍ରାକ୍ କରନ୍ତୁ',
    featureTrackDesc: 'ଆପଣଙ୍କର ଆବେଦନ ଅଗ୍ରଗତି ଉପରେ ରିଅଲ୍-ଟାଇମ୍ ଅପଡେଟ୍ |'
  },
  ml: {
    title: 'എഡുഗ്രാന്റ്',
    home: 'ഹോം',
    browse: 'സ്കോളർഷിപ്പുകൾ',
    dashboard: 'ഡാഷ്ബോർഡ്',
    login: 'ലോഗിൻ / സൈൻ അപ്പ്',
    logout: 'ലോഗ് ഔട്ട്',
    apply: 'അപേക്ഷിക്കുക',
    applyPrompt: 'അപേക്ഷിക്കാൻ ലോഗിൻ ചെയ്യുക',
    searchPlaceholder: 'സ്കോളർഷിപ്പുകൾ തിരയുക...',
    heroTitle: 'നിങ്ങളുടെ ഭാവി സുരക്ഷിതമാക്കൂ',
    heroDesc: 'ഇന്ത്യയിലെ മികച്ച സ്കോളർഷിപ്പുകൾ കണ്ടെത്തി അപേക്ഷിക്കുക.',
    filter: 'ഫിൽട്ടർ',
    deadline: 'അവസാന തീയതി',
    amount: 'തുക',
    eligibility: 'യോഗ്യത',
    status: 'അവസ്ഥ',
    welcome: 'സ്വാഗതം',
    profileSetup: 'പ്രൊഫൈൽ പൂർത്തിയാക്കുക',
    college: 'കോളേജ് പേര്',
    cgpa: 'നിലവിലെ CGPA',
    class12: 'പ്ലസ് ടു മാർക്ക് (%)',
    submit: 'സമർപ്പിക്കുക',
    emailPlaceholder: 'നിങ്ങളുടെ ഇമെയിൽ നൽകുക',
    otpPlaceholder: 'OTP നൽകുക ',
    getOtp: 'OTP നേടുക',
    verify: 'പരിശോധിച്ച് ലോഗിൻ ചെയ്യുക',
    featureSearchTitle: 'എളുപ്പത്തിലുള്ള തിരയൽ',
    featureSearchDesc: 'നിങ്ങളുടെ അക്കാദമിക് പ്രൊഫൈലിന് അനുയോജ്യമായ സ്കോളർഷിപ്പുകൾ കണ്ടെത്തുക.',
    featureApplyTitle: 'ഒറ്റ ക്ലിക്ക് അപേക്ഷ',
    featureApplyDesc: 'പരിശോധിച്ച വിദ്യാർത്ഥികൾക്കായി ലളിതമായ അപേക്ഷാ നടപടികൾ.',
    featureTrackTitle: 'സ്റ്റാറ്റസ് ട്രാക്ക് ചെയ്യുക',
    featureTrackDesc: 'നിങ്ങളുടെ അപേക്ഷയുടെ പുരോഗതിയെക്കുറിച്ചുള്ള തത്സമയ വിവരങ്ങൾ.'
  }
};